//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11334\r\n6264\r\n9318\r\n\r\n1209\r\n4404\r\n3988\r\n5816\r\n3890\r\n4990\r\n2796\r\n4199\r\n5439\r\n4249\r\n2938\r\n1120\r\n2612\r\n\r\n1755\r\n12840\r\n6995\r\n1547\r\n13621\r\n3701\r\n\r\n5499\r\n3383\r\n3991\r\n6695\r\n2008\r\n2478\r\n5240\r\n4782\r\n6979\r\n4205\r\n5604\r\n\r\n15226\r\n5377\r\n14173\r\n\r\n20230\r\n2467\r\n12544\r\n\r\n1565\r\n12373\r\n2270\r\n16050\r\n15570\r\n\r\n9085\r\n5182\r\n16013\r\n13189\r\n3946\r\n\r\n6852\r\n4248\r\n4724\r\n7276\r\n1360\r\n5716\r\n2826\r\n7027\r\n6205\r\n2153 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay1 {
            get {
                return ResourceManager.GetString("InputDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Z
        ///A Z
        ///B Z
        ///C Z
        ///C Z
        ///B X
        ///A X
        ///C X
        ///A Z
        ///C Y
        ///C X
        ///C Y
        ///C Y
        ///A X
        ///A Z
        ///A Z
        ///A X
        ///B Z
        ///B X
        ///A Z
        ///A X
        ///C Y
        ///A X
        ///B Z
        ///B Z
        ///A X
        ///C Z
        ///A Z
        ///A X
        ///B Z
        ///A Z
        ///A Y
        ///C Y
        ///A Z
        ///C Z
        ///A Z
        ///C Y
        ///C Z
        ///C Z
        ///A Z
        ///A X
        ///A X
        ///B X
        ///A Z
        ///B Z
        ///A X
        ///A Z
        ///A Z
        ///A X
        ///A X
        ///C Y
        ///A Z
        ///B X
        ///C Y
        ///A X
        ///B Y
        ///A Z
        ///A X
        ///A Z
        ///A X
        ///C Z
        ///A Z
        ///A Y
        ///A X
        ///C Y
        ///A X
        ///B X
        ///A X
        ///A Z
        ///C Y
        ///A Z
        ///A X
        ///C X
        ///C Z
        ///C Z
        ///A Z
        ///A X
        ///A Z
        ///C X
        ///C Z
        ///B Z
        ///A Z
        ///C Y
        ///C Z
        ///B X
        ///A X
        ///A Z
        ///A X
        ///A X
        ///C Y
        ///A Z
        ///C Z
        ///B X
        ///A X
        ///A X
        ///A Z
        ///A Y
        ///A X
        ///C X
        ///A Z
        ///B X
        ///C Y
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay2 {
            get {
                return ResourceManager.GetString("InputDay2", resourceCulture);
            }
        }
    }
}
