//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11334\r\n6264\r\n9318\r\n\r\n1209\r\n4404\r\n3988\r\n5816\r\n3890\r\n4990\r\n2796\r\n4199\r\n5439\r\n4249\r\n2938\r\n1120\r\n2612\r\n\r\n1755\r\n12840\r\n6995\r\n1547\r\n13621\r\n3701\r\n\r\n5499\r\n3383\r\n3991\r\n6695\r\n2008\r\n2478\r\n5240\r\n4782\r\n6979\r\n4205\r\n5604\r\n\r\n15226\r\n5377\r\n14173\r\n\r\n20230\r\n2467\r\n12544\r\n\r\n1565\r\n12373\r\n2270\r\n16050\r\n15570\r\n\r\n9085\r\n5182\r\n16013\r\n13189\r\n3946\r\n\r\n6852\r\n4248\r\n4724\r\n7276\r\n1360\r\n5716\r\n2826\r\n7027\r\n6205\r\n2153 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay1 {
            get {
                return ResourceManager.GetString("InputDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Z
        ///A Z
        ///B Z
        ///C Z
        ///C Z
        ///B X
        ///A X
        ///C X
        ///A Z
        ///C Y
        ///C X
        ///C Y
        ///C Y
        ///A X
        ///A Z
        ///A Z
        ///A X
        ///B Z
        ///B X
        ///A Z
        ///A X
        ///C Y
        ///A X
        ///B Z
        ///B Z
        ///A X
        ///C Z
        ///A Z
        ///A X
        ///B Z
        ///A Z
        ///A Y
        ///C Y
        ///A Z
        ///C Z
        ///A Z
        ///C Y
        ///C Z
        ///C Z
        ///A Z
        ///A X
        ///A X
        ///B X
        ///A Z
        ///B Z
        ///A X
        ///A Z
        ///A Z
        ///A X
        ///A X
        ///C Y
        ///A Z
        ///B X
        ///C Y
        ///A X
        ///B Y
        ///A Z
        ///A X
        ///A Z
        ///A X
        ///C Z
        ///A Z
        ///A Y
        ///A X
        ///C Y
        ///A X
        ///B X
        ///A X
        ///A Z
        ///C Y
        ///A Z
        ///A X
        ///C X
        ///C Z
        ///C Z
        ///A Z
        ///A X
        ///A Z
        ///C X
        ///C Z
        ///B Z
        ///A Z
        ///C Y
        ///C Z
        ///B X
        ///A X
        ///A Z
        ///A X
        ///A X
        ///C Y
        ///A Z
        ///C Z
        ///B X
        ///A X
        ///A X
        ///A Z
        ///A Y
        ///A X
        ///C X
        ///A Z
        ///B X
        ///C Y
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay2 {
            get {
                return ResourceManager.GetString("InputDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPZTzDhJPLqPhqDTqrwQZZWbmCBMJMcsNmCBFWmMcsNb
        ///vplSlfdfGvfRRGsgNcMglsFWMWMC
        ///jtjvFHdjjwqrwqwL
        ///NSffhsNSjfLjfstsjtjNNjjqMqnpggHngqgHGHCgClGbCzCC
        ///dDPZZDZFdwFWwFZFWZRTFDwGzCMlgnpgCpnzglClHMbg
        ///DTPFZQRcdTVNhbjVbcLc
        ///JZLDcSZSpHHrrLrJcpzBRrhlzgRTmTmvBRmm
        ///qQsQMCbMQWqCVVvmTRhTTRhCRhTg
        ///svbGWPqGPNLJSpZnZpnN
        ///wLtPGCLwfWLflCPtPfLLTSbHMbSgMdtvDHghhHvdgZ
        ///nNsFznJcJqzFFszFqrNnRzdbZDDbRMbMdRHbMdgHvZSd
        ///VczNnjsrFrjcNprqVwTPfjGllWPQBBWlgB
        ///nnGtjFFjFTTTGtBGmWBTWffLcMJMQlzjQPCPcChCQDJzDJJd
        ///SSggbHVbZRgZsHZRHdVhzCcJhzhMzJhQPQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay3 {
            get {
                return ResourceManager.GetString("InputDay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22-77,14-96
        ///7-99,65-98
        ///22-36,37-62
        ///25-94,24-67
        ///6-91,1-6
        ///88-88,2-88
        ///27-89,58-96
        ///21-82,9-94
        ///38-79,27-80
        ///4-90,30-55
        ///84-97,52-93
        ///12-59,11-12
        ///4-14,5-12
        ///50-84,49-89
        ///3-98,1-3
        ///91-95,8-22
        ///15-66,17-67
        ///27-27,27-90
        ///36-37,37-96
        ///31-32,32-80
        ///1-79,2-78
        ///36-85,20-36
        ///2-2,2-98
        ///33-81,80-99
        ///4-73,45-72
        ///3-89,1-4
        ///6-92,21-91
        ///7-93,2-92
        ///47-89,47-50
        ///64-84,63-65
        ///22-85,21-91
        ///16-31,11-14
        ///4-93,3-93
        ///15-61,61-62
        ///21-23,22-88
        ///59-59,11-58
        ///23-23,22-89
        ///19-87,78-86
        ///13-82,19-83
        ///22-88,76-92
        ///46-47,46-46
        ///30-31, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay4 {
            get {
                return ResourceManager.GetString("InputDay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [V]     [B]                     [C]
        ///[C]     [N] [G]         [W]     [P]
        ///[W]     [C] [Q] [S]     [C]     [M]
        ///[L]     [W] [B] [Z]     [F] [S] [V]
        ///[R]     [G] [H] [F] [P] [V] [M] [T]
        ///[M] [L] [R] [D] [L] [N] [P] [D] [W]
        ///[F] [Q] [S] [C] [G] [G] [Z] [P] [N]
        ///[Q] [D] [P] [L] [V] [D] [D] [C] [Z]
        /// 1   2   3   4   5   6   7   8   9.
        /// </summary>
        internal static string InputDay51 {
            get {
                return ResourceManager.GetString("InputDay51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move 1 from 9 to 2
        ///move 4 from 6 to 1
        ///move 4 from 2 to 6
        ///move 5 from 8 to 7
        ///move 4 from 9 to 2
        ///move 1 from 5 to 8
        ///move 1 from 3 to 1
        ///move 2 from 3 to 1
        ///move 1 from 4 to 2
        ///move 11 from 7 to 2
        ///move 5 from 5 to 1
        ///move 1 from 6 to 8
        ///move 1 from 7 to 6
        ///move 3 from 6 to 7
        ///move 1 from 3 to 2
        ///move 1 from 6 to 8
        ///move 11 from 2 to 1
        ///move 1 from 9 to 8
        ///move 1 from 3 to 7
        ///move 4 from 7 to 9
        ///move 3 from 3 to 7
        ///move 4 from 8 to 2
        ///move 3 from 7 to 6
        ///move 2 from 6 to 3
        ///move 5 from 4 to 1
        ///move 1 fro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay52 {
            get {
                return ResourceManager.GetString("InputDay52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mzrzqrzqrrmcmgmrggvjvcczbczccdwdcwcpwwclwwbttdntnsnllpggqhgqgzqggvjjjfqfhhbbvzvmzvvfccnznwntnptpgpcplpwwvgvzvvcgvvbcvcqqhnqqbsbdsbbbgtgvtgvtgvvrfvvjbjcbcchnhrhvvrmmwzwzmwmggjwwwwzrrmbmbmbrrdjrjfrrrmrffzgghtggwddtllhchdhsshjjwfwsfssnbbnjncczsczzvpvssljsjgsjgjcgjggspsfsfhfppsqqzlzjllblsldsldlndnhnffflwfwmwssvzzvqzzblzbbmrrfnrrqnnhfnnhphbhrrlvrlvrvcrrltrtmrrcscchdhqhfffrddzsszwwrbrfftddbwwtdtnndrrghgcgfgrglllcdcsswvwsvszsddjwdwwcvwvmvhhlqlddbhbrrnddpqpttrtctmcmjjtvjjfvvlcldltdtdqdllnrncrnrznzfnfsfnndqqbhhlnhhh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay6 {
            get {
                return ResourceManager.GetString("InputDay6", resourceCulture);
            }
        }
    }
}
